# import class derived
from driver import driver

# membuat object dan print driver1
d1 = driver()
d1.setNIK("327301")
d1.setName("Fahreza")
d1.setGen("Male")
d1.setNIP("359001")
d1.setCompany("Jatayu Airways")
d1.setPos("Flight Engineer")
d1.setID("90901101")
d1.setUntil("December,2025")
d1.setVehicle("Airplane")
print("**********************************")
print("Driver 1")
print("**********************************")
d1.printPerson()
d1.printJob()
d1.printDriver()

# membuat object dan print driver2
d2 = driver()
d2.setNIK("327302")
d2.setName("Fadhil")
d2.setGen("Male")
d2.setNIP("359002")
d2.setCompany("Jatayu Airways")
d2.setPos("Ground Engineer")
d2.setID("90901102")
d2.setUntil("January,2024")
d2.setVehicle("Airplane")
print("**********************************")
print("Driver 2")
print("**********************************")
d2.printPerson()
d2.printJob()
d2.printDriver()

# membuat object dan print driver3
d3 = driver()
d3.setNIK("327305")
d3.setName("Nabhan")
d3.setGen("Male")
d3.setNIP("359005")
d3.setCompany("Jatayu Airways")
d3.setPos("Pilot")
d3.setID("90901105")
d3.setUntil("November,2025")
d3.setVehicle("Airplane")
print("**********************************")
print("Driver 3")
print("**********************************")
d3.printPerson()
d3.printJob()
d3.printDriver()

# membuat object dan print driver4
d4 = driver()
d4.setNIK("327303")
d4.setName("Reydi")
d4.setGen("Male")
d4.setNIP("359003")
d4.setCompany("Jatayu Airways")
d4.setPos("Co-Pilot")
d4.setID("90901103")
d4.setUntil("July,2026")
d4.setVehicle("Airplane")
print("**********************************")
print("Driver 4")
print("**********************************")
d4.printPerson()
d4.printJob()
d4.printDriver()

# membuat object dan print driver5
d5 = driver()
d5.setNIK("327304")
d5.setName("Hawwa")
d5.setGen("Female")
d5.setNIP("359004")
d5.setCompany("Jatayu Airways")
d5.setPos("Crew Cabin")
d5.setID("90901104")
d5.setUntil("August,2025")
d5.setVehicle("Airplane")
print("**********************************")
print("Driver 5")
print("**********************************")
d5.printPerson()
d5.printJob()
d5.printDriver()
