# import child_1 and child_2
from airplane import airplane
from ship import ship

print("AIRPLANE TYPE\n")

# membuat object dan print airplane1
a1 = airplane()
a1.setTypeAir("B747-100")
a1.setAgeAir(60)
a1.setWing(59.6)
a1.setBody(70.6)
a1.setTall(19.3)
a1.setCabin(6.1)
a1.setFuel("Aftur")
a1.setMax(452)
print("**********************************")
print("Airplane 1")
print("**********************************")
a1.printAirplane()
a1.printVehicle()

# membuat object dan print airplane2
a2 = airplane()
a2.setTypeAir("B747-300")
a2.setAgeAir(46)
a2.setWing(64.4)
a2.setBody(70.6)
a2.setTall(19.4)
a2.setCabin(6.1)
a2.setFuel("Aftur")
a2.setMax(524)
print("**********************************")
print("Airplane 2")
print("**********************************")
a2.printAirplane()
a2.printVehicle()

# membuat object dan print airplane3
a3 = airplane()
a3.setTypeAir("B787-8")
a3.setAgeAir(10)
a3.setWing(60.1)
a3.setBody(56.7)
a3.setTall(16.9)
a3.setCabin(5.49)
a3.setFuel("Aftur")
a3.setMax(242)
print("**********************************")
print("Airplane 3")
print("**********************************")
a3.printAirplane()
a3.printVehicle()

# membuat object dan print airplane4
a4 = airplane()
a4.setTypeAir("B787-10")
a4.setAgeAir(2)
a4.setWing(60.1)
a4.setBody(68.3)
a4.setTall(17.2)
a4.setCabin(5.49)
a4.setFuel("Aftur")
a4.setMax(330)
print("**********************************")
print("Airplane 4")
print("**********************************")
a4.printAirplane()
a4.printVehicle()

# membuat object dan print airplane5
a5 = airplane()
a5.setTypeAir("A350-800")
a5.setAgeAir(4)
a5.setWing(64.74)
a5.setBody(60.55)
a5.setTall(17.10)
a5.setCabin(5.61)
a5.setFuel("Aftur")
a5.setMax(270)
print("**********************************")
print("Airplane 5")
print("**********************************")
a5.printAirplane()
a5.printVehicle()

print("CRUISER TYPE\n")

# membuat object dan print ship1
s1 = ship()
s1.setTypeShip("Royal Wonder of the Seas")
s1.setAgeShip(1)
s1.setManu("Miami, Florida")
s1.setFuel("Diesel")
s1.setMax(6988)
print("**********************************")
print("Cruiser 1")
print("**********************************")
s1.printShip()
s1.printVehicle()

# membuat object dan print ship2
s2 = ship()
s2.setTypeShip("Royal Harmony of the Seas")
s2.setAgeShip(5)
s2.setManu("Miami, Florida")
s2.setFuel("Diesel")
s2.setMax(6687)
print("**********************************")
print("Cruiser 2")
print("**********************************")
s2.printShip()
s2.printVehicle()

# membuat object dan print ship3
s3 = ship()
s3.setTypeShip("AIDAnova")
s3.setAgeShip(3)
s3.setManu("Rostock, Germany")
s3.setFuel("Diesel")
s3.setMax(6654)
print("**********************************")
print("Cruiser 3")
print("**********************************")
s3.printShip()
s3.printVehicle()

# membuat object dan print ship4
s4 = ship()
s4.setTypeShip("AIDAcosma")
s4.setAgeShip(1)
s4.setManu("Rostock, Germany")
s4.setFuel("Diesel")
s4.setMax(6600)
print("**********************************")
print("Cruiser 4")
print("**********************************")
s4.printShip()
s4.printVehicle()

# membuat object dan print ship5
s5 = ship()
s5.setTypeShip("MSC Grandiosa")
s5.setAgeShip(2)
s5.setManu("Geneva, Switzterland")
s5.setFuel("Diesel")
s5.setMax(6761)
print("**********************************")
print("Cruiser 5")
print("**********************************")
s5.printShip()
s5.printVehicle()
